### ISSUE TITLE
Card flip bugs

### ISSUE THREAD

**Issue by peterbabic** [mimoguz/tripeaks-gdx#6] opened 2021-05-05 06:06 UTC
Hello,
the game is nice but there are some issues, screenshots below.

Hearts 10 flipped top left:
![Screenshot_20210503-215503](https://user-images.githubusercontent.com/3952052/117102249-39a92800-ad78-11eb-97e9-85f19f3503e7.png)
Top left card not flipped:
![Screenshot_20210503-223411](https://user-images.githubusercontent.com/3952052/117102252-3a41be80-ad78-11eb-905d-88ebf681223d.png)
Two entry row cards not flipped:
![Screenshot_20210505-025025](https://user-images.githubusercontent.com/3952052/117102253-3ada5500-ad78-11eb-8fb8-321cb8d7a1ed.png)
One entry row card not flipped:
![Screenshot_20210505-025603](https://user-images.githubusercontent.com/3952052/117102255-3b72eb80-ad78-11eb-8fa7-d25f806aedc5.png)
Black 5 flipped in the middle, but should not be:
![Screenshot_20210505-025643](https://user-images.githubusercontent.com/3952052/117102257-3b72eb80-ad78-11eb-98a6-364bcd16cee6.png)
Red 2 flipped in the middle:
![Screenshot_20210505-025838](https://user-images.githubusercontent.com/3952052/117102258-3c0b8200-ad78-11eb-920b-dce7243c9760.png)
The same red 2 even disappeared:
![Screenshot_20210505-025853](https://user-images.githubusercontent.com/3952052/117102259-3c0b8200-ad78-11eb-9e29-7163b21d695b.png)

**Comment by mimoguz** [comment] 2021-05-05 06:36
Uh, weird. Can you check which version you have? I play it every day, never saw something like that since version 0.1. Button graphics say it's a later version though :( Can you try purging and re-installing, just in case?

**Comment by mimoguz** [comment] 2021-05-05 06:48
Also, which version of Android do you have?

**Comment by peterbabic** [comment] 2021-05-05 07:44
@mimoguz I have version 0.44 installed via F-Droid on Android 9.

Most of the bugs seem to be related to a situation when there is the same card twice. Can you please confirm/reject that it shouldn't be possible? I believe all cards on the desk should be unique. When due to some unknown reason the same card gets on the different positions, the problems occur.

I have purged the game but had not played it yet since.

**Comment by mimoguz** [comment] 2021-05-05 07:54
All cards must be unique. Game logic is pretty simple, and there should be nothing that can cause this behaviour. Previous issue was just a stupid mistake with indexes when checking neighbours.  I'll try running in Android 9 emulator, but I have no idea what's going on :(

**Comment by peterbabic** [comment] 2021-05-05 07:56
Currently, I have been playing for around 4 days sporadically, but the first 2 days shown no bugs whatsoever. Once they started, they are quite common. So it could be that something happened to device, but still strange.

**Comment by mimoguz** [comment] 2021-05-05 08:00
Quite strange yes.

**Comment by mimoguz** [comment] 2021-05-05 08:26
I played the game a few times in an emulator running Android 9 while watching collections. So far, no problems, no duplication whatsoever. I'll add some more checks and try again, might be some obscure bug somewhere.

**Comment by peterbabic** [comment] 2021-05-06 18:14
It happened after reinstall too.

**Comment by mimoguz** [comment] 2021-05-08 12:42
Hi. Sorry for late response. I've made a few revisions and will put up a beta in a few days (When I'm better or too bored :D . I've got the virus unfortunately.) Though, I don't know if it will fix the issue, since I can't replicate.

**Comment by peterbabic** [comment] 2021-05-08 12:56
No! Get out the bed, I need this business critical piece of software bug-free right now! And you rather respond to me right away next time! 

Just kidding 😄  I mean, no need to excuse for "late responses". Remember, we are doing this for fun. And get well soon! 🙏🏻

**Comment by xxxxme** [comment] 2021-05-09 00:48
I'm using 0.44 from F-Droid on Android 9 also.
I got an extra 10 of hearts on the upper left. It flipped over when I drew the 10 of hearts from the draw pile, and at this point it could be taken as if it were uncovered. (I play with covered cards hidden.)
Here's the original deal, with the extra 10 beside the first in the draw pile, since that's where it went when I hit undo.
![Screenshot_20210508-202759_TriPeaks](https://user-images.githubusercontent.com/3073154/117557196-8aea3d80-b03e-11eb-89e1-cf68217c6219.png)
Edit: It looks like it's replacing the king of spades.

**Comment by mimoguz** [comment] 2021-05-18 20:18
Hi again.

I released a test version on the Google Play Store. Could you please try that? It will just crash if there are really duplicate cards. 

[Join testing program](https://play.google.com/apps/testing/ogz.tripeaks)
[Play Store link](https://play.google.com/store/apps/details?id=ogz.tripeaks)

Thanks.

PS. I can create an apk if you want. Play Store test releases are signed and I assume checked tough, so should be safer than a random apk.

**Comment by xxxxme** [comment] 2021-05-18 20:33
It would have to be an apk posted here or uploaded to f-droid, for me. I don't have a Google account, so I can't join the testing program.

**Comment by mimoguz** [comment] 2021-05-19 07:44
[Apks are here](https://github.com/mimoguz/tripeaks-test-releases/releases/tag/6a)

**Comment by izaleu** [comment] 2021-07-05 17:16
Just chiming in to say I've also experienced this issue, it started happening after an update but I can't remember which one 💀

**Comment by mimoguz** [comment] 2021-07-05 17:51
Problem with this issue is I can't reproduce it at all! No updates except first a few and 0.46 touched the game mechanics, and 0.46 should have fixed only possible cause I could think. ☹ 

I guess at the end I will need to sit down and re-write entire view logic. I suck at programming. 😁

**Comment by izaleu** [comment] 2021-07-05 19:09
> Problem with this issue is I can't reproduce it at all! No updates except first a few and 0.46 touched the game mechanics, and 0.46 should have fixed only possible cause I could think. ☹
> 
> I guess at the end I will need to sit down and re-write entire view logic. I suck at programming. 😁

It's very hard to reproduce! I will definitely update if I get any more info.

**Comment by mimoguz** [comment] 2021-08-04 11:01
Would you please check the 0.5 branch test release: [tripeaks-test-releases/releases/tag/0.5b1](https://github.com/mimoguz/tripeaks-test-releases/releases/tag/0.5b1)

I rewrote most of the game logic and rendering parts, much simpler now.  Are the problems still persist?

Thanks.

**Comment by mimoguz** [comment] 2021-08-15 10:29
Since I couldn't get a response, I'm closing this issue for now.

**Closed as completed by mimoguz** 2021-08-15 10:29 UTC
Labels: bug

**Comment by peterbabic** [comment] 2021-08-15 11:04
@mimoguz Hello, I checked when you last wrote 0.5 is out, but at that time I could only get 0.4 something from F-Droid and forgot about it since.

**Comment by mimoguz** [comment] 2021-08-15 11:09
No problem :) The new release should be on F-Droid sometime next week. Please let me know if the issue persists. Thanks.
